-- UnVeilmi demo data
-- Prices recalculated with the current backend pricing rule:
-- Free tier: ciphertext <= 1024 bytes AND storage_hours <= 24 => USD 0
-- Otherwise: ceil((ciphertext_bytes / 1024) * (storage_hours / 24) * USD 1)
-- Runtime fields such as id, ciphertext_size, created_at, and expires_at
-- are generated by the database schema/trigger when these INSERTs run.

BEGIN TRANSACTION;

INSERT INTO posts (article_name, ciphertext, storage_hours, price)
VALUES (
    'did you get home',
    'VEILMI1:eyJ2IjoxLCJrIjoiUEJLREYyLVNIQTI1NiIsImkiOjUwMDAwLCJzIjoiNmtXdld6QTNUYm1wMURRcHJUanJJQT09IiwibiI6Iks1UzRCT0NyNFVraHgzNHEiLCJjIjoibHhzbms0MVpSekVjb1dNRGllZ2c1UmxWIiwibSI6Ild2U0hkd3dMMEZpOXZ0THlQUGtFR3c9PSJ9',
    24,
    0
);

INSERT INTO posts (article_name, ciphertext, storage_hours, price)
VALUES (
    'yeah just got back',
    'VEILMI1:eyJ2IjoxLCJrIjoiUEJLREYyLVNIQTI1NiIsImkiOjUwMDAwLCJzIjoiQXBzOWlkc0hKNnpkemktck1BZExRUT09IiwibiI6IkVLRmVyX1A0eFV0TzllV3EiLCJjIjoiNGpRRVlFc2ktWmx6SzNaeXFQX0pSZXM5QVhEci1IR19iV0lXQ204X095N19ON3pDZk1ZPSIsIm0iOiJqdXBsX25XbUNnNHEzSEZnc1ltT0hRPT0ifQ==',
    36,
    1
);

INSERT INTO posts (article_name, ciphertext, storage_hours, price)
VALUES (
    'did you eat yet',
    'VEILMI1:eyJ2IjoxLCJrIjoiUEJLREYyLVNIQTI1NiIsImkiOjUwMDAwLCJzIjoiejZuSzlhQTlfbWYyS2tScFk3ZVVVQT09IiwibiI6IjZ1U3lud3pEd0Z0VU55REEiLCJjIjoiUUtEcGZsVnI2eXE2WmE0Zk9yVWlfQk5kNUptX0tsbnFIOTVPOTQ5MW9aZmNDcUtCeEQ0Ym5zVlhUV1dfTGg5bmFYMGNpRFplZC1CMWRoaTlBTUl1R3ZHWTBkR0FFMnh0IiwibSI6Im41djFSaW9UVVF4YkkzYkRVMFVFRGc9PSJ9',
    48,
    1
);

INSERT INTO posts (article_name, ciphertext, storage_hours, price)
VALUES (
    'not really hungry',
    'VEILMI1:eyJ2IjoxLCJrIjoiUEJLREYyLVNIQTI1NiIsImkiOjUwMDAwLCJzIjoid2FDU2Y1d0N3M3JVV0oyN0Z2VjB3QT09IiwibiI6IjVLUXZBT19yZnBEWXhUMW8iLCJjIjoiYXpDRUFfd2ZLQmpJb0tUTEplN1RYcHU4WV94R3puSkhPTHRmbE5LV19BcjdfX28zLVlUNGUwdkpjVlcxZDhQOV8zZG1FcTNpTTNwQ3hkc1dDVExRMHV5Y1pVdHF4Y0w3c1RfVGNtRjJ3dVl4RXFCYVlxX2NvSklHQkx3UGJBPT0iLCJtIjoiTC1kQVlqeVllTjQtMDFFR3JlSGNOUT09In0=',
    60,
    1
);

INSERT INTO posts (article_name, ciphertext, storage_hours, price)
VALUES (
    'maybe order something',
    'VEILMI1:eyJ2IjoxLCJrIjoiUEJLREYyLVNIQTI1NiIsImkiOjUwMDAwLCJzIjoiWGRJeG01OW9WQjRUdEpQMmdDQ1B6QT09IiwibiI6Ijl4bGgxTHZ2eHJ4MGRyeGwiLCJjIjoiNTVNUXAxTHVJOS1SNXd6QzJmcjM4NFJGZHFSVFZCd1lJeDhtYTJQRVB4d1hOT1JwNFJXdUc2RzNMVnBrS3hja0podXY5WDQ3cHVYRUdNVTYwMDFzU0Q3ZDNTOHYwSjJYMEE9PSIsIm0iOiJGMUsycGFhUDBQQi1ZSVZKWjM4LUh3PT0ifQ==',
    72,
    1
);

INSERT INTO posts (article_name, ciphertext, storage_hours, price)
VALUES (
    'i might cook later',
    'VEILMI1:eyJ2IjoxLCJrIjoiUEJLREYyLVNIQTI1NiIsImkiOjUwMDAwLCJzIjoibzQ5eENFdjJyTThQaG1PXzhMQU05dz09IiwibiI6IlZiVV9HRThwNURsSHFYUkkiLCJjIjoiN0JucFZEbkk4WjdVbEN0WkhmbXBZaHhJOGtyOEpxX29lUzhaNDJ0STRNaENDUmxIenEyVmduMUxiaXVud2VORS11UjI5bHhvdlA5d1FCUzZVNWJEZTREMi1tdGsxOXVoNVBZbFJqY291RDRveGxvPSIsIm0iOiIxOGlwTUtjTFVOUU9jYVVWakVsc0FBPT0ifQ==',
    84,
    2
);

INSERT INTO posts (article_name, ciphertext, storage_hours, price)
VALUES (
    'weather looks nice',
    'VEILMI1:eyJ2IjoxLCJrIjoiUEJLREYyLVNIQTI1NiIsImkiOjUwMDAwLCJzIjoiMV9peGlleTd2QnAwOTJ5d0pIRWIydz09IiwibiI6IlhhSGNWYlJ6S0dPMURyYnIiLCJjIjoibUkyV2paU0tHWmNDRUt4b3VCWGFydllUT0ZQWkw0elJsME9WcFRzeS1DMUZsVFpqT1dfSk1rc2NnbVdHb2g4a1RUdndhQl9XbjN6VEtxblVfWjJuRmN4a1Y0QTlqUTVQelJPZ29EdVRIdlYyZTl3PSIsIm0iOiJya3A2NEkzWkJyR2FaTUp6Q1pYU0xBPT0ifQ==',
    96,
    2
);

INSERT INTO posts (article_name, ciphertext, storage_hours, price)
VALUES (
    'maybe go for a walk',
    'VEILMI1:eyJ2IjoxLCJrIjoiUEJLREYyLVNIQTI1NiIsImkiOjUwMDAwLCJzIjoiRExycDlOV19xR05KR2w5UTEwcUVDQT09IiwibiI6IklUWWpqb0haNnl1WTFvR1oiLCJjIjoiZXA3dzE1MDVCZGlKVE9Pb0loWFJuc3pnWmU0TldBMVp5YU5nLVFwcDZUeFlqbldKNXB0YWxaMjY2YlRHd280T3pzSWRyZ2stNThiSmZiakZ1LXl0X0E4eTFaMHQxT29ISGVVQmhSVUNtdlVFIiwibSI6IndSa1puc0RwX3dWMG0wZDNRbndRRGc9PSJ9',
    108,
    2
);

INSERT INTO posts (article_name, ciphertext, storage_hours, price)
VALUES (
    'i will check later',
    'VEILMI1:eyJ2IjoxLCJrIjoiUEJLREYyLVNIQTI1NiIsImkiOjUwMDAwLCJzIjoiRExhQ2xoWVVFeEdqYW11UldfT0xVdz09IiwibiI6Im9tSVhLTEpta2VXNHV6dkQiLCJjIjoiQ2NBa0lwWmQ0X3RPNFNuRFhnM2FVTWx6UUR4MUh1eWItS19leDlqYXJ0aURZRUM2ZTNWV1V5NkY4aG04WDJGN2NoVHRJNzIzcmRtOGpmT25FOEwtZnoyWjgtMjBGOWVDd0c0TndaRy1taWNlQW04RXlOaUZOazdpX1JPd3pCdndiZUdvWjhvR0lnLUNZZVhMMk8xbVNtYz0iLCJtIjoiMkNQaUZhOXA1bkxBT0QycWxWaHR0dz09In0=',
    120,
    2
);

INSERT INTO posts (article_name, ciphertext, storage_hours, price)
VALUES (
    'okay talk tonight',
    'VEILMI1:eyJ2IjoxLCJrIjoiUEJLREYyLVNIQTI1NiIsImkiOjUwMDAwLCJzIjoiSzN3d2RyUnBSd200bnpERF9ORjV3UT09IiwibiI6IllLa205bFNYUWNrLWxNN0MiLCJjIjoiOFJ6YUl5V25OMkZLZGpxMWRrLTkzdUt4NkRtcWlkUV8yTmNKek5TR3o4cEhERnNIN2dwS2F2TV9Za0UyaHdoLXphZ01MOWo2Ty14OVl2Z3BBVFhfWFBIWTJvSjY3dXpaWVJYdTVBUTE3WXBZWThfbG5mcEsteVlmY1JDbXpRb0NZYUhQVURVOG51cz0iLCJtIjoiVTlmcFp4TGpCeF9BWFJ5Um9UQXpsQT09In0=',
    132,
    2
);

COMMIT;
